apiVersion: v1
kind: ConfigMap
metadata:
  name: my-env-configmap
data:
  message: Hello, World!
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-file-configmap
data:
  app.cfg: |
    key1=value1
    key2=value2
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-env-pod
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'echo $MESSAGE']
    env:
    - name: MESSAGE
      valueFrom:
        configMapKeyRef:
          name: my-env-configmap
          key: message
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-file-pod
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'cat /config/app.cfg']
    volumeMounts:
    - name: config
      mountPath: /config
      readOnly: true
  volumes:
  - name: config
    configMap:
      name: my-file-configmap
      items:
      - key: app.cfg
        path: app.cfg
