apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: badgers.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                firstColour:
                  type: string
                secondColour:
                  type: string
                legs:
                  type: integer
  scope: Cluster
  names:
    plural: badgers
    singular: badger
    kind: Badger
    shortNames:
    - br
